lexik_jwt_authentication:
  secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
  public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
  pass_phrase:      'cb84c21a3809edbb805f6d66298c4e87' # required for token creation, usage of an environment variable is recommended
  token_ttl:        86400