twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    paths:
         '%kernel.project_dir%/public/logo': img
         '%kernel.project_dir%/public/styles': style
         '%kernel.project_dir%/templates/report': report
    globals:
        report_storage: '%env(PUBLIC_REPORT_STORAGE_LINK)%'
        app_environment: '%env(FRONT_BASE_URL)%'